apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    user: admin
    password: secretpassword
    url: http://influxdb:8086
    isDefault: true
    editable: true
    secureJsonData:
      token: mytoken
    jsonData:
          version: Flux
          organization: myorg
          defaultBucket: mybucket
          tlsSkipVerify: true